apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
        name: gophish
    name: gophish
spec:
    replicas: 1
    template:
        metadata:
            labels:
                name: gophish
        spec:
            containers:
                name: gophish
                image: asia.gcr.io/${PROJECT_ID}/${CONTAINER_NAME}:latest
                ports:
                    - containerPort: 3333
