apiVersion: v1
kind: Service
metadata:
  labels:
    name: gophish
  name: gophish
spec:
  ports:
  - port: 3333
    targetPort: 3333
    protocol: TCP
  selector:
    name: gophish
  type: NodePort
  #type: LoadBalancer
